// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL0aZRab5egBtOLXDsFoi2W9smu6-w3UA',
    appId: '1:261786614236:android:1747208506ed73a34b7719',
    messagingSenderId: '261786614236',
    projectId: 'pathguard-ai-2d047',
    databaseURL: 'https://pathguard-ai-2d047-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pathguard-ai-2d047.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFSc1cQ1tWujS3v93foORFBpUsiGuWaU',
    appId: '1:261786614236:ios:1658ae5be59e62b74b7719',
    messagingSenderId: '261786614236',
    projectId: 'pathguard-ai-2d047',
    databaseURL: 'https://pathguard-ai-2d047-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pathguard-ai-2d047.firebasestorage.app',
    iosBundleId: 'com.pathguard.pathguardApp',
  );
}
